# Generated by Django 3.1.5 on 2021-04-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20210402_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_card',
            name='user',
        ),
        migrations.AlterField(
            model_name='create_card',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='create_card',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
