# Generated by Django 3.1.5 on 2021-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20210403_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_card',
            name='english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='create_card',
            name='urdu',
            field=models.BooleanField(default=False),
        ),
    ]
