# Generated by Django 3.1.5 on 2021-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20210403_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_card',
            name='languages',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
