# Generated by Django 3.1.5 on 2021-04-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20210403_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_card',
            name='languages',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
